"""The HTML page must restate summary.md faithfully: same tables, same numbers, right verdicts."""
import os

from alnfail.html import build_html, parse_markdown, parse_rate, pretty_number, render_table, verdict

SUMMARY = """# Results digest

Generated by `python -m alnfail report`.

## 1. Headline: placement accuracy and the MAPQ 30 promise

A MAPQ of 30 claims at most 1 wrong alignment per 1,000.

| platform | aligner | reads | wrong per 1,000 at MAPQ≥30 | × the promised 1 per 1,000 |
|---|---|---|---|---|
| illumina | minimap2 | 48,000 | 0.62 (0.43–0.89) | 0.62 |
| illumina | bwamem2 | 48,000 | 2.50 (1.90–3.20) | 2.50 |
| hifi | ngmlr | 800 | 0.00 (0.00–5.02) | 0.00 |

## 3. Hardest genomic contexts

**Toy genome, illumina** (misplaced, % of reads)

| stratum_set | stratum | bowtie2 | minimap2 |
|---|---|---|---|
| segdup | SD_>=99% | 10.27 | 10.46 |
| repeat_class | none | 0 | 0.5 |

## 4. Is the simulator realistic? (task 3)

| dataset | metric | real | simulated | ok |
|---|---|---|---|---|
| toy | mismatch_rate | 0.001 | 0.0011 | True |
| toy | del_rate | 4.307e-05 | 6.343e-05 | False |

## Figures

- `fig_accuracy.png`: Misplaced and unmapped reads.
"""

# the smallest valid PNG: one transparent pixel
PNG = bytes.fromhex("89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c489"
                    "0000000d49444154789c6360000002000001e221bc330000000049454e44ae426082")


def test_markdown_blocks():
    blocks = parse_markdown(SUMMARY)
    kinds = [b[0] for b in blocks]
    assert kinds.count("h2") == 4 and kinds.count("table") == 3 and kinds.count("ul") == 1
    header, rows = next(b[1:] for b in blocks if b[0] == "table")
    assert header[1] == "aligner" and len(rows) == 3  # the |---| rule is not a data row
    assert rows[0][3] == "0.62 (0.43–0.89)"


def test_rate_and_number_formatting():
    assert parse_rate("0.62 (0.43–0.89)") == (0.62, 0.43, 0.89)
    assert parse_rate("no reads") is None
    assert pretty_number("1e+03") == "1,000"
    assert pretty_number("4.307e-05") == "4.31 × 10⁻⁵"
    assert pretty_number("0.0007918") == "0.0007918"  # ordinary numbers are not touched


def test_verdict_uses_the_whole_interval():
    assert verdict(0.43, 0.89, 1.0) == "within"  # entirely below the claim
    assert verdict(1.90, 3.20, 1.0) == "above"   # entirely above it
    assert verdict(0.00, 5.02, 1.0) == "open"    # straddles it: too few reads to decide


def test_failed_checks_come_first_and_are_marked():
    table = render_table(["metric", "ok"], [["a", "True"], ["b", "False"]])
    assert table.index("✕ no") < table.index("✓ yes")
    assert 'class="flagged"' in table


def test_page_is_self_contained_and_complete(tmp_path):
    (tmp_path / "summary.md").write_text(SUMMARY, encoding="utf-8")
    (tmp_path / "fig_accuracy.png").write_bytes(PNG)
    (tmp_path / "fig_unlisted.png").write_bytes(PNG)
    page = open(build_html(str(tmp_path)), encoding="utf-8").read()

    assert os.path.exists(tmp_path / "report.html")
    assert page.count("data:image/png;base64,") == 2      # both figures embedded, listed or not
    assert "More figures" in page                          # the unlisted one is not silently dropped
    assert "http://" not in page and "https://" not in page  # nothing is loaded from the network
    for number in ("48,000", "0.62 (0.43–0.89)", "10.46", "4.31 × 10⁻⁵"):
        assert number in page
    for state, expected in (("above", 1), ("within", 1), ("open", 1)):  # one row of each kind above
        assert page.count(f'class="verdict {state}"') == expected
    assert "× the promised" not in page                    # the redundant column is replaced by the ruler
    assert "SD ≥ 99%" in page                              # identifiers are shown as words
